# Generated by Django 5.2.17 on 2026-09-22 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle', models.CharField(max_length=20)),
                ('tokens', models.PositiveSmallIntegerField()),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('provider', models.CharField(max_length=20)),
                ('provider_order_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('created', 'Awaiting payment'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='created', max_length=10)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('kind', models.CharField(choices=[('purchase', 'Purchase'), ('enrolment', 'Enrolment'), ('adjustment', 'Adjustment')], max_length=12)),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrolment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_entry', to='classes.enrolment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_entries', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entry', to='payments.tokenpurchase')),
            ],
            options={
                'verbose_name_plural': 'token entries',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='tokenpurchase',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_order_id'), name='unique_provider_order'),
        ),
        migrations.AddConstraint(
            model_name='tokenentry',
            constraint=models.CheckConstraint(condition=models.Q(('delta', 0), _negated=True), name='token_entry_non_zero'),
        ),
    ]
