# Generated by Django 4.0.6 on 2022-07-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='students',
            field=models.ManyToManyField(blank=True, to='APE.students'),
        ),
    ]
