# Generated by Django 4.0.6 on 2022-11-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APE', '0002_alter_classes_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='zoom_ID',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='classes',
            name='zoom_link',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='classes',
            name='zoom_password',
            field=models.CharField(max_length=30),
        ),
    ]
