# Generated by Django 4.0.6 on 2023-02-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APE', '0003_alter_classes_zoom_id_alter_classes_zoom_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorapplications',
            name='accepted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
