# Generated by Django 4.0.6 on 2023-02-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APE', '0004_mentorapplications_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorapplications',
            old_name='accepted',
            new_name='decided',
        ),
    ]
