# Generated by Django 5.2.17 on 2026-09-22 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_requests', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='catalog.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutoringClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(choices=[(30, '30 min'), (45, '45 min'), (60, '1 hr'), (90, '1 hr 30 min'), (120, '2 hr')], default=60)),
                ('meeting_url', models.URLField(max_length=500, verbose_name='Zoom link')),
                ('meeting_id', models.CharField(blank=True, max_length=32, verbose_name='Zoom meeting ID')),
                ('meeting_passcode', models.CharField(blank=True, max_length=32, verbose_name='Zoom passcode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='accounts.mentorprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='catalog.subject')),
                ('subtopics', models.ManyToManyField(related_name='classes', to='catalog.subtopic')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_spent', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to=settings.AUTH_USER_MODEL)),
                ('tutoring_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='classes.tutoringclass')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='tutoringclass',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='class_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.UniqueConstraint(fields=('tutoring_class', 'student'), name='one_enrolment_per_student_per_class'),
        ),
    ]
