"""Builds docs/EVALS.md from evals/results/*.json and the hand-written evals/decision.md."""

import json
from pathlib import Path

from django.conf import settings

from .evals import CASES, EVAL_NOW


def _pct(x):
    return "n/a" if x is None else f"{x:.0%}"


def _num(x, fmt="{:.1f}"):
    return "n/a" if x is None else fmt.format(x)


def write_report(results_dir) -> Path:
    runs = [json.loads(p.read_text()) for p in sorted(Path(results_dir).glob("*.json"))]
    runs.sort(key=lambda r: (-r["summary"]["clean_plan_rate"], -r["summary"]["valid_plan_rate"]))
    cases = json.loads(CASES.read_text())
    decision = Path(settings.BASE_DIR) / "evals" / "decision.md"
    lines = [
        "# Study-planner evals",
        "",
        "Generated by `python manage.py run_evals --report`. Don't edit by hand; the decision",
        "section comes from `evals/decision.md`.",
        "",
        f"{len(cases)} fixed cases (`evals/cases.json`) across AP Chemistry, AP Physics 1 and AP",
        "Calculus AB: typical plans, one-week and two-week sprints, exams far enough away that the",
        "plan is capped at 16 weeks, one hour a week and twenty, no weak units and all of them,",
        "no classes and a class almost every week. Each case runs through `run_model`, the same",
        "code the page uses, including the one corrective retry. The context is built as of",
        f"{EVAL_NOW:%Y-%m-%d} with fixed class ids, so every run sends identical prompts and the",
        "recorded responses in `evals/cassettes/` replay without a key.",
        "",
        "## What's measured",
        "",
        "| Metric | Meaning |",
        "|---|---|",
        "| Valid | A plan with no rule breaks came back within two attempts (what a user gets) |",
        "| First try | No rule breaks on the first attempt (how often the retry is needed) |",
        "| Clean | Valid, and no quality warnings either |",
        "| Warnings/plan | Quality problems per valid plan: a unit never covered, a weak unit "
        "started late, a class recommended in a week that doesn't study its topics, a week with "
        "no tasks |",
        "| Class use | Share of the available live classes the plan recommends |",
        "| Latency, tokens | Median wall time per plan (all attempts) and mean tokens in + out |",
        "",
        "Rule breaks are an invented topic or class, a class in the wrong week, more hours than "
        "the student has, and wrong week numbering (`planner/checks.py`).",
        "",
        "## Results",
        "",
        "| Model | Prompt | Valid | First try | Clean | Warnings/plan | Class use "
        "| Median latency | Mean tokens |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for run in runs:
        s = run["summary"]
        lines.append(
            f"| `{s['model']}` | {s.get('prompt', '')} | {_pct(s['valid_plan_rate'])} "
            f"| {_pct(s['first_attempt_rate'])} "
            f"| {_pct(s['clean_plan_rate'])} | {_num(s['warnings_per_plan'], '{:.2f}')} "
            f"| {_pct(s['class_use'])} | {_num(s['median_latency_ms'], '{:,.0f} ms')} "
            f"| {_num(s['mean_tokens'], '{:,.0f}')} |"
        )
    lines += [
        "",
        "## Warnings by type",
        "",
        "| Model | "
        + " | ".join(
            sorted({w for r in runs for w in r["summary"]["warning_counts"]}) or ["(none)"]
        )
        + " |",
    ]
    kinds = sorted({w for r in runs for w in r["summary"]["warning_counts"]})
    lines.append("|---|" + "---|" * max(1, len(kinds)))
    for run in runs:
        counts = run["summary"]["warning_counts"]
        cells = [str(counts.get(k, 0)) for k in kinds] or ["0"]
        label = f"`{run['summary']['model']}` {run['summary'].get('prompt', '')}"
        lines.append(f"| {label} | " + " | ".join(cells) + " |")
    lines += [
        "",
        "## Per case",
        "",
        "PASS = clean, ok = valid with warnings, FAIL = no valid plan.",
        "",
        "| Case | "
        + " | ".join(f"`{r['summary']['model']}` {r['summary'].get('prompt', '')}" for r in runs)
        + " |",
        "|---|" + "---|" * len(runs),
    ]
    by_model = [{c["case"]: c for c in r["cases"]} for r in runs]
    for case in cases:
        cells = []
        for results in by_model:
            r = results.get(case["id"])
            if r is None:
                cells.append("")
            elif not r["ok"]:
                cells.append("FAIL")
            else:
                cells.append("PASS" if not r["warnings"] else "ok: " + ", ".join(r["warnings"]))
        lines.append(f"| {case['id']} | " + " | ".join(cells) + " |")
    if decision.exists():
        lines += ["", decision.read_text().strip()]
    path = Path(settings.BASE_DIR) / "docs" / "EVALS.md"
    path.write_text("\n".join(lines) + "\n")
    return path
