# Generated by Django 5.2.17 on 2026-09-23 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('starts_on', models.DateField(help_text='First day of week 1.')),
                ('hours_per_week', models.PositiveSmallIntegerField()),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('ok', 'Ready'), ('failed', 'Failed')], max_length=10)),
                ('plan', models.JSONField(blank=True, null=True)),
                ('problems', models.JSONField(blank=True, default=list)),
                ('model', models.CharField(max_length=100)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
                ('weak_units', models.ManyToManyField(blank=True, related_name='+', to='catalog.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
